# Generated by Django 5.1.5 on 2025-02-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="file",
        ),
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
    ]
